name: CI/CD Deploy Google Cloud

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas basicas
        run: npm test

      - name: Construir imagen Docker
        run: docker build -t proyecto-devops-so-final .

      - name: Desplegar en Google Cloud por SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          port: 22
          script: |
            cd ~/proyecto-devops-so-final
            git pull origin main
            docker compose down
            docker compose up -d --build
            docker ps