name: CI/CD Deploy Google Cloud

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas basicas
        run: npm test

      - name: Construir imagen Docker
        run: docker build -t proyecto-devops-so-final .

      - name: Preparar llave SSH
        run: |
          mkdir -p ~/.ssh
          printf '%s' "${{ secrets.GCP_SSH_KEY_B64 }}" | base64 -d > ~/.ssh/gcp_key
          chmod 600 ~/.ssh/gcp_key

      - name: Mostrar llave publica generada por GitHub Actions
        run: |
          ssh-keygen -y -f ~/.ssh/gcp_key > ~/.ssh/gcp_key.pub
          echo "COPIA ESTA LINEA COMPLETA:"
          cat ~/.ssh/gcp_key.pub
          echo "HUELLA:"
          ssh-keygen -lf ~/.ssh/gcp_key.pub

      - name: Probar conexion SSH
        run: |
          ssh -i ~/.ssh/gcp_key -o IdentitiesOnly=yes -o StrictHostKeyChecking=no lopezkike255@35.253.218.105 "whoami"

      - name: Desplegar en Google Cloud
        run: |
          ssh -i ~/.ssh/gcp_key -o IdentitiesOnly=yes -o StrictHostKeyChecking=no lopezkike255@35.253.218.105 "
            cd ~/proyecto-devops-so-final &&
            git pull origin main &&
            docker compose down &&
            docker build -t proyecto-devops-so-final-app:latest . &&
            docker stack deploy -c docker-stack.yml devops_stack &&
            docker service update --force devops_stack_app &&
            docker service ls
          "