name: CI/CD Deploy Google Cloud

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas basicas
        run: npm test

      - name: Construir imagen Docker
        run: docker build -t proyecto-devops-so-final .

      - name: Preparar llave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_KEY_B64 }}" | base64 -d > ~/.ssh/gcp_key
          chmod 600 ~/.ssh/gcp_key

      - name: Probar conexion SSH
        run: |
          ssh -i ~/.ssh/gcp_key -o StrictHostKeyChecking=no ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST }} "whoami"

      - name: Desplegar en Google Cloud
        run: |
          ssh -i ~/.ssh/gcp_key -o StrictHostKeyChecking=no ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST }} "
            cd ~/proyecto-devops-so-final &&
            git pull origin main &&
            docker compose down &&
            docker compose up -d --build &&
            docker ps
          "